# Generated by Django 4.2.7 on 2024-01-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.TextField(max_length=250),
        ),
    ]
