# Generated by Django 4.2.7 on 2024-01-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0003_class_student_class_n"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatar"),
        ),
    ]
