# Generated by Django 4.2.7 on 2024-01-30 00:56

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0004_student_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(blank=True, null=True)),
                ("lastname", models.CharField(blank=True, null=True)),
                ("age", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name="student",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=student.models.avatar_file_name
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="class_n",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student",
                to="student.class",
            ),
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book",
                        to="student.author",
                    ),
                ),
            ],
        ),
    ]
