# Generated by Django 5.0.1 on 2024-02-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0005_author_alter_student_avatar_alter_student_class_n_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
